server:
  port: 8083

spring:
  application:
    name: microservicio_users
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/users?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    config:
      uri: http://config-server:8888
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          # Microservicio Reports
          - id: maintenance_controller
            uri: http://localhost:8082
            predicates:
              - Path=/api/maintenances/**
          - id: reports_controller
            uri: http://localhost:8082
            predicates:
            - Path=/api/reports/**

          # Microservicio Stops
          - id: stop_controller
            uri: http://localhost:8081
            predicates:
              - Path=/api/stops/**
          - id: scooter_controller
            uri: http://localhost:8081
            predicates:
              - Path=/api/scooters**
          - id: admin_controller
            uri: http://localhost:8081
            predicates:
              - Path=/api/admin/**

          # Microservicio Travels
          - id: travels_controller
            uri: http://localhost:8080
            predicates:
              - Path=/api/travels/**
          - id: travel_stop_controller
          - uri: http://localhost:8080
          - predicates:
              - Path=/api/travel-stop/**
          - id: billing_controller
            uri: http://localhost:8080
            predicates:
              - Path=/api/billings/**
          - id: billing_methods_controller
            uri: http://localhost:8080
            predicates:
              - Path=/api/billing-methods/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/


